# Generated by Django 4.2.1 on 2023-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_candy_alter_exercise_options_alter_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='candies',
            field=models.ManyToManyField(to='main_app.candy'),
        ),
    ]
